/**
 * renderPlanMarkdown — PlanDocument -> Markdown, one direction only.
 *
 * This replaces the old flow where Markdown was the source of truth and
 * `PlanGenerator.extractTodos()` used regex to parse `- [ ]` lines back out
 * of it. Under Plan V2, `PlanTask[]` is authoritative; this function is a
 * pure view. Nothing should ever parse this output back into task data —
 * if you need task data, read it from PlanDocument / PlanSession directly.
 *
 * The output format intentionally stays close to the old 6-section plan
 * (Context / Questions / Architecture / TODOs / Risks / Approval) so it can
 * drop into the existing PlanEditor / PlanReview UI without a UI rewrite —
 * see PlanModeControllerAdapter.ts.
 */
import type { PlanDocument, TaskStatus } from './schema';

const STATUS_BADGE: Record<TaskStatus, string> = {
  pending: ' ',
  in_progress: '~',
  blocked: '!',
  satisfied: 'x',
  awaiting_verification: '?',
  verified: 'x',
  failed: '!'
};

export function renderPlanMarkdown(
  doc: PlanDocument,
  researchContext = '',
  taskStatus: Readonly<Record<string, TaskStatus>> = {}
): string {
  const lines: string[] = [];

  lines.push('## Context', '', researchContext || doc.goal || 'No research context provided.', '');
  lines.push('## Summary', '', doc.summary, '');

  lines.push('## Tasks', '');
  for (const task of doc.tasks) {
    const status = taskStatus[task.id] ?? 'pending';
    const badge = STATUS_BADGE[status] ?? ' ';
    lines.push(`- [${badge}] **${task.id}**: ${task.title}${status === 'verified' ? ' ✓ verified' : ''}`);
    lines.push(`  ${task.description}`);
    if (task.files.length > 0) {
      lines.push(`  - files: ${task.files.map((f) => `${f.path} (${f.intent})`).join(', ')}`);
    }
    if (task.dependencies.length > 0) {
      lines.push(`  - depends on: ${task.dependencies.join(', ')}`);
    }
    if (task.verification.length > 0) {
      lines.push(`  - verify: ${task.verification.join('; ')}`);
    }
  }
  lines.push('');

  lines.push('## Risks', '');
  if (doc.risks.length > 0) {
    for (const r of doc.risks) lines.push(`- ⚠️ **${r.risk}**: ${r.mitigation}`);
  } else {
    lines.push('No risks identified.');
  }
  lines.push('');

  lines.push(
    '## Approval',
    '',
    '---',
    '',
    '**Review the plan above.**',
    '',
    '- [ ] I have reviewed the tasks and risks',
    '',
    '---',
    '*Plan generated by Agent-K Plan Mode (V2 — structured)*'
  );

  return lines.join('\n');
}
