/**
 * V31-CTX-02 — CompactionStrategy + SummaryProvider.
 *
 * The synchronous placeholders in CompactionEngine stay as a fast fallback;
 * this module adds an async path whose summary text is generated by the model
 * (or by an injected SummaryProvider), while user instructions are protected.
 */

import type { AgentMessage } from '../../types';
import type { CompactLevel } from '../CompactionEngine';

/** Minimal context passed to a strategy. */
export interface CompactionContext {
  /** Model window in tokens. */
  maxTokens: number;
  /** Messages protected from compaction (system + user + recent turns). */
  protected: AgentMessage[];
  /** Messages eligible for compaction. */
  unprotected: AgentMessage[];
  /** Drop-duplicate-reads bookkeeping from the preceding drop pass. */
  droppedCount: number;
}

export interface CompactionResult {
  level: CompactLevel;
  messages: AgentMessage[];
  droppedCount: number;
}

/**
 * A single compaction level. Strategies are registered by level so the engine
 * can be extended without editing a switch statement (QG4).
 */
export interface CompactionStrategy {
  readonly level: CompactLevel;
  /** Apply the strategy to unprotected messages and reassemble the transcript. */
  compact(
    messages: AgentMessage[],
    protectedMsgs: AgentMessage[],
    unprotected: AgentMessage[],
    droppedCount: number
  ): CompactionResult;
}

/**
 * Produces a natural-language summary of messages within a token budget.
 * Implementations may call a model; a template fallback is provided.
 */
export interface SummaryProvider {
  summarize(messages: AgentMessage[], budgetTokens: number): Promise<string>;
}

/** Fallback that never calls a model — deterministic template. */
export class TemplateSummaryProvider implements SummaryProvider {
  async summarize(messages: AgentMessage[]): Promise<string> {
    const userAsks = messages
      .filter((m) => m.role === 'user' && !m.metadata?.type)
      .map((m) => m.content.trim())
      .filter(Boolean);
    const toolNames = Array.from(
      new Set(
        messages
          .filter((m) => m.role === 'tool')
          .map((m) => m.metadata?.toolName ?? m.name)
          .filter(Boolean) as string[]
      )
    );
    const lines = [
      `[compaction summary] ${messages.length} earlier messages compressed.`,
    ];
    if (userAsks.length) {
      lines.push(
        `Prior user instructions (preserved): ${userAsks.map((u) => JSON.stringify(u)).join('; ')}`
      );
    }
    if (toolNames.length) {
      lines.push(`Tools used: ${toolNames.join(', ')}.`);
    }
    return lines.join('\n');
  }
}

/** Signature of the model runner injected from the host (dependency inversion). */
export type SummaryRunModelFn = (input: {
  messages: AgentMessage[];
  signal?: AbortSignal;
}) => Promise<{ content?: string; reasoning?: string }>;

/**
 * Uses the injected model runner to summarize. Falls back to the template when
 * the model returns nothing or throws.
 */
export class ModelSummaryProvider implements SummaryProvider {
  constructor(
    private readonly runModel: SummaryRunModelFn,
    private readonly fallback: SummaryProvider = new TemplateSummaryProvider(),
    private readonly maxSummaryTokens = 512
  ) {}

  async summarize(messages: AgentMessage[], budgetTokens: number): Promise<string> {
    const budget = Math.min(budgetTokens, this.maxSummaryTokens);
    const prompt: AgentMessage = {
      role: 'user',
      content: [
        'Summarize the conversation above for context compaction.',
        'Preserve all explicit user instructions, constraints, and decisions verbatim.',
        'Keep it under roughly ' + budget + ' tokens.',
        'Do not invent actions that were not taken.',
      ].join('\n'),
      metadata: { type: 'compaction_prompt', protected: true },
    };
    try {
      const result = await this.runModel({
        messages: [...messages, prompt],
      });
      const text = result.content?.trim();
      if (text) return text;
    } catch {
      // fall through to template
    }
    return this.fallback.summarize(messages, budget);
  }
}
