/**
 * Config domain barrel — CFG-001 ConfigManager, CFG-002 ProjectConfig, CFG-003 Permission.
 */

export {
  AGENT_K_FEATURES_CONFIG_KEYS,
  AGENT_K_VSCODE_CONFIG_KEYS,
  ConfigManager,
  configManager,
  createDefaultConfig,
  type ConfigListener,
  type ConfigStorage,
  type VSCodeConfigUpdater,
} from './ConfigManager';

export {
  AGENTK_DIR,
  PROJECT_CONFIG_FILENAMES,
  PROJECT_CONFIG_KEYS,
  PROJECT_CONFIG_LEGACY_FILENAMES,
  PROJECT_CONFIG_PATH,
  exampleProjectConfig,
  exampleProjectConfigJson,
  flattenProjectConfig,
  parseProjectConfigJson,
  pickProjectConfigValues,
  unflattenProjectConfig,
  type ParseProjectConfigResult,
} from './ProjectConfig';

export {
  CFG003_FLAT_KEYS,
  DEFAULT_DENY_GLOBS,
  DEFAULT_PERMISSION_LEVEL,
  DEFAULT_REQUIRE_APPROVAL_TOOLS,
  PERMISSION_CONFIG_DEFAULTS,
  PERMISSION_FLAT_KEYS,
  PERMISSION_GATED_TOOL_NAMES,
  PERMISSION_LEVELS,
  WRITE_GATE_POLICY_FLAT_KEYS,
  WRITE_TOOL_NAMES,
  extractPermissionConfig,
  extractPermissionSettings,
  extractWriteGatePolicySettings,
  isPathDenied,
  isPermissionGatedToolName,
  isPermissionLevel,
  isWriteToolName,
  matchGlobPattern,
  mergePermissionSettings,
  normalizeDenyGlobs,
  normalizeStringList,
  parseForceOnComplex,
  parsePermissionLevel,
  parseRequireApprovalTools,
  permissionConfigToFlat,
  toolRequiresExplicitApproval,
  validatePermissionConfigValue,
  type Cfg003FlatKey,
  type PermissionConfigBundle,
  type PermissionConfigIssue,
  type PermissionConfigIssueCode,
  type PermissionConfigParseResult,
  type PermissionFlatKey,
  type PermissionLevel,
  type PermissionSettings,
  type WriteGatePolicyFlatKey,
  type WriteGatePolicySettings,
} from './PermissionConfig';
