/**
 * PlanGenerator - 계획 문서 생성 (C5-T04)
 * 
 * 6섹션 스키마:
 * 1. Context — 현재 상황 / 문제 정의
 * 2. Questions — Clarifying Questions 답변 요약
 * 3. Architecture — Mermaid 다이어그램 (before/after)
 * 4. TODOs — 체크리스트 (step-by-step)
 * 5. Risks — 위험 요소 및 완화 방안
 * 6. Approval — 서명/승인 섹션
 * 
 * 경로: `.agentk/plans/PLAN-<slug>.md`
 */

export interface PlanDocument {
  slug: string;
  title: string;
  content: string;
  sections: PlanSection[];
  todoCount: number;
  createdAt: number;
}

export interface PlanSection {
  id: string;
  title: string;
  content: string;
}

export class PlanGenerator {
  /**
   * Generate a complete plan document from research context and questions
   */
  generatePlan(params: {
    title: string;
    researchContext: string;
    questions: Array<{ question: string; answer: string }>;
    architectureMermaid: string;
    todos: string[];
    risks: Array<{ risk: string; mitigation: string }>;
  }): PlanDocument {
    const slug = this.slugify(params.title);
    const sections = this.buildSections(params);
    const content = this.assembleDocument(sections);

    return {
      slug,
      title: params.title,
      content,
      sections,
      todoCount: params.todos.length,
      createdAt: Date.now()
    };
  }

  /**
   * Generate a Mermaid flowchart from a high-level description
   */
  generateMermaidFlowchart(steps: string[]): string {
    const lines: string[] = ['```mermaid', 'graph TD'];
    steps.forEach((step, i) => {
      const id = `S${i + 1}`;
      const label = step.replace(/[^a-zA-Z0-9가-힣\s]/g, '').trim().slice(0, 40);
      lines.push(`    ${id}[${label}]`);
      if (i > 0) lines.push(`    S${i} --> ${id}`);
    });
    lines.push('```');
    return lines.join('\n');
  }

  /**
   * Generate a Mermaid sequence diagram for before/after comparison
   */
  generateMermaidBeforeAfter(before: string[], after: string[]): string {
    const lines: string[] = ['```mermaid', 'sequenceDiagram'];
    lines.push('    participant User');
    before.forEach((step, i) => {
      lines.push(`    User->>System: ${step.slice(0, 50)} (before)`);
    });
    lines.push('    Note over System: REFACTOR');
    after.forEach((step, i) => {
      lines.push(`    User->>System: ${step.slice(0, 50)} (after)`);
    });
    lines.push('```');
    return lines.join('\n');
  }

  private buildSections(params: {
    researchContext: string;
    questions: Array<{ question: string; answer: string }>;
    architectureMermaid: string;
    todos: string[];
    risks: Array<{ risk: string; mitigation: string }>;
  }): PlanSection[] {
    return [
      {
        id: 'context',
        title: 'Context',
        content: params.researchContext || 'No research context provided.'
      },
      {
        id: 'questions',
        title: 'Questions',
        content: params.questions.length > 0
          ? params.questions.map(q => `- **${q.question}**: ${q.answer}`).join('\n')
          : 'No clarifying questions were asked.'
      },
      {
        id: 'architecture',
        title: 'Architecture',
        content: params.architectureMermaid || 'No architecture diagram provided.'
      },
      {
        id: 'todos',
        title: 'TODOs',
        content: params.todos.length > 0
          ? params.todos.map((t, i) => `- [ ] **Step ${i + 1}**: ${t}`).join('\n')
          : '- [ ] No steps defined.'
      },
      {
        id: 'risks',
        title: 'Risks',
        content: params.risks.length > 0
          ? params.risks.map(r => `- ⚠️ **${r.risk}**: ${r.mitigation}`).join('\n')
          : 'No risks identified.'
      },
      {
        id: 'approval',
        title: 'Approval',
        content: [
          '---',
          '',
          '**Review the plan above.**',
          '',
          '- [ ] I have reviewed the architecture and TODOs',
          '- [ ] I understand the risks',
          '',
          '---',
          '*Plan generated by Agent-K Plan Mode*'
        ].join('\n')
      }
    ];
  }

  private assembleDocument(sections: PlanSection[]): string {
    const lines: string[] = [];
    
    sections.forEach((section, i) => {
      if (i > 0) lines.push('');
      lines.push(`## ${section.title}`);
      lines.push('');
      lines.push(section.content);
    });

    return lines.join('\n');
  }

  /**
   * Parse a completed plan document back into sections
   */
  parseDocument(content: string): PlanSection[] {
    const sections: PlanSection[] = [];
    const sectionRegex = /## (.+?)\n\n([\s\S]*?)(?=\n## |$)/g;
    let match;

    while ((match = sectionRegex.exec(content)) !== null) {
      sections.push({
        id: this.slugify(match[1]),
        title: match[1].trim(),
        content: match[2].trim()
      });
    }

    return sections;
  }

  /**
   * Extract TODO items from plan content
   */
  extractTodos(content: string): string[] {
    const todos: string[] = [];
    const todoRegex = /- \[ \] \*\*Step \d+\*\*: (.+)/g;
    let match;
    while ((match = todoRegex.exec(content)) !== null) {
      todos.push(match[1].trim());
    }
    return todos;
  }

  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9가-힣]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60);
  }
}

export const planGenerator = new PlanGenerator();
